environment:
  matrix:
    - PYTHON: "C:\\Python27"
install:
  - "git submodule update --init --recursive"
  - "%PYTHON%\\python.exe -m pip install -r Documentation/requirements.txt"
build_script:
  - "%PYTHON%\\python.exe -m pip install --target lib/site-packages --process-dependency-links -r requirements.txt"
  - "Documentation/make.bat html"
after_build:
  - 7z a -tzip -xr!.* -xr0!build build\\WuLiFang-Nuke-%APPVEYOR_REPO_TAG_NAME%-win.zip
artifacts:
  - path: build\WuLiFang-Nuke-*.zip
    name: Prebuild package
before_deploy:
  - ps: >-
      & $env:PYTHON\\python.exe Documentation/get_changelog.py $env:APPVEYOR_REPO_TAG_NAME build/release_note.md;
      ${env:APPVEYOR_RELEASE_DESCRIPTION} = (Get-Content -Encoding utf8 build/release_note.md) -join "`n";
deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_RELEASE_DESCRIPTION)
  provider: GitHub
  auth_token:
    secure: F3Yyeg/9CKfhBQ6baTP5XsOqnquey/5hXl1EtPqmk0WptSzV6STE7M4Pa+BJnTZ2
  artifact: /.*\.zip/            
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true